import { createReadStream, existsSync, statSync } from "node:fs"
import { extname, join, normalize, resolve, sep } from "node:path"
import { defineConfig, type Plugin } from "vite"
import { fileURLToPath, URL } from "node:url"
import { tanstackStart } from "@tanstack/react-start/plugin/vite"
import viteReact from "@vitejs/plugin-react"
import viteTsConfigPaths from "vite-tsconfig-paths"
import tailwindcss from "@tailwindcss/vite"

const SHELL_MIME_TYPES: Record<string, string> = {
  ".css": "text/css",
  ".html": "text/html",
  ".ico": "image/x-icon",
  ".js": "text/javascript",
  ".json": "application/json",
  ".map": "application/json",
  ".mjs": "text/javascript",
  ".png": "image/png",
  ".svg": "image/svg+xml",
  ".webmanifest": "application/manifest+json",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
}

/**
 * Serves `/desktop-shell/*` from the freshly built desktop bundle during development.
 *
 * Installed desktop packages fetch their UI from the backend origin they were compiled against,
 * which for engineering builds is this server. Without this, that request falls through to
 * `public/desktop-shell/`, a directory only regenerated by a full `bun run build:web` — so an
 * installed app kept rendering whatever shell happened to be committed to the public directory
 * and could never match the site being served. `bun run build:desktop:ui` is now enough.
 */
function desktopShellDevServer(): Plugin {
  const shellRoot = fileURLToPath(new URL("./dist/desktop", import.meta.url))

  return {
    name: "millennium-desktop-shell-dev",
    apply: "serve",
    configureServer(server) {
      server.middlewares.use((request, response, next) => {
        const rawUrl = request.url || "/"
        if (!rawUrl.startsWith("/desktop-shell/")) return next()

        const requestedPath = decodeURIComponent(rawUrl.split("?")[0]).slice("/desktop-shell/".length)
        const target = resolve(shellRoot, normalize(requestedPath))
        if (target !== shellRoot && !target.startsWith(shellRoot + sep)) {
          response.statusCode = 400
          response.end("Invalid shell path")
          return
        }
        if (!existsSync(target) || !statSync(target).isFile()) return next()

        response.setHeader(
          "Content-Type",
          SHELL_MIME_TYPES[extname(target).toLowerCase()] || "application/octet-stream"
        )
        response.setHeader("Cache-Control", "no-store")
        createReadStream(target).pipe(response)
      })
      server.watcher.add(join(shellRoot, "shell.json"))
    },
  }
}

export default defineConfig({
  optimizeDeps: {
    // Portal sync runs exclusively on the server. Prebundling these packages
    // for browser targets makes esbuild reject yargs' Node.js ESM/CJS interop
    // export (`module.exports`).
    exclude: ["puppeteer-core", "@puppeteer/browsers", "yargs", "jsdom"],
  },
  server: {
    host: "localhost",
    port: 3000,
    strictPort: true,
  },
  preview: {
    host: "localhost",
    port: 3000,
    strictPort: true,
  },
  ssr: {
    noExternal: ["@lobehub/icons"],
  },
  build: {
    // Keep generated bundles distinct from the public /Assets brand directory.
    // macOS treats `assets` and `Assets` as the same path, which previously
    // replaced one directory with the other and broke CSS/chunk requests.
    assetsDir: "_app-assets",
    chunkSizeWarningLimit: 1000,
    rollupOptions: {
      onLog(level, log, defaultHandler) {
        if (
          level === "warn" &&
          log.code === "UNUSED_EXTERNAL_IMPORT" &&
          typeof log.id === "string" &&
          log.id.includes("node_modules/")
        ) {
          return
        }

        defaultHandler(level, log)
      },
    },
  },
  resolve: {
    alias: {
      "@": fileURLToPath(new URL(".", import.meta.url)),
    },
  },
  plugins: [
    desktopShellDevServer(),
    viteTsConfigPaths({
      projects: ["./tsconfig.json"],
    }),
    tailwindcss(),

    tanstackStart(),
    viteReact(),
  ],
})
