/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppOpenIndexRouteImport } from './routes/app-open.index'
import { Route as AppOpenRouteImport } from './routes/app/open'
import { Route as ApiReadinessRouteImport } from './routes/api/readiness'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiUserThemeBuilderRouteImport } from './routes/api/user/theme-builder'
import { Route as ApiUserProfileImageRouteImport } from './routes/api/user/profile-image'
import { Route as ApiUserPreferencesRouteImport } from './routes/api/user/preferences'
import { Route as ApiUserNotificationsRouteImport } from './routes/api/user/notifications'
import { Route as ApiUserLocalCalendarRouteImport } from './routes/api/user/local-calendar'
import { Route as ApiUserExportRouteImport } from './routes/api/user/export'
import { Route as ApiUserAccountRouteImport } from './routes/api/user/account'
import { Route as ApiThemesExploreRouteImport } from './routes/api/themes/explore'
import { Route as ApiStudyWorkshopRouteImport } from './routes/api/study/workshop'
import { Route as ApiStudyUndoRouteImport } from './routes/api/study/undo'
import { Route as ApiStudyTrialRouteImport } from './routes/api/study/trial'
import { Route as ApiStudySyncRouteImport } from './routes/api/study/sync'
import { Route as ApiStudySessionsRouteImport } from './routes/api/study/sessions'
import { Route as ApiStudyReviewsRouteImport } from './routes/api/study/reviews'
import { Route as ApiStudyQueueRouteImport } from './routes/api/study/queue'
import { Route as ApiStudyPreferencesRouteImport } from './routes/api/study/preferences'
import { Route as ApiStudyPlanningRouteImport } from './routes/api/study/planning'
import { Route as ApiStudyNotesRouteImport } from './routes/api/study/notes'
import { Route as ApiStudyMigrateRouteImport } from './routes/api/study/migrate'
import { Route as ApiStudyMediaRouteImport } from './routes/api/study/media'
import { Route as ApiStudyImportRouteImport } from './routes/api/study/import'
import { Route as ApiStudyFlashcardsRouteImport } from './routes/api/study/flashcards'
import { Route as ApiStudyExportRouteImport } from './routes/api/study/export'
import { Route as ApiStudyDecksRouteImport } from './routes/api/study/decks'
import { Route as ApiStudyCutoverRouteImport } from './routes/api/study/cutover'
import { Route as ApiStudyBrowserRouteImport } from './routes/api/study/browser'
import { Route as ApiStudyBootstrapRouteImport } from './routes/api/study/bootstrap'
import { Route as ApiStudyAnalyticsRouteImport } from './routes/api/study/analytics'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiReportsPdfRouteImport } from './routes/api/reports/pdf'
import { Route as ApiReportsAnnotationsRouteImport } from './routes/api/reports/annotations'
import { Route as ApiPortalSyncRouteImport } from './routes/api/portal/sync'
import { Route as ApiPortalLoginRouteImport } from './routes/api/portal/login'
import { Route as ApiPortalDataRouteImport } from './routes/api/portal/data'
import { Route as ApiPortalAccountRouteImport } from './routes/api/portal/account'
import { Route as ApiPastPapersShareRouteImport } from './routes/api/past-papers/share'
import { Route as ApiPastPapersSavesRouteImport } from './routes/api/past-papers/saves'
import { Route as ApiPastPapersReindexRouteImport } from './routes/api/past-papers/reindex'
import { Route as ApiPastPapersPreferencesRouteImport } from './routes/api/past-papers/preferences'
import { Route as ApiPastPapersPdfRouteImport } from './routes/api/past-papers/pdf'
import { Route as ApiPastPapersLibraryRouteImport } from './routes/api/past-papers/library'
import { Route as ApiPastPapersBrowseRouteImport } from './routes/api/past-papers/browse'
import { Route as ApiPastPapersAttemptsRouteImport } from './routes/api/past-papers/attempts'
import { Route as ApiPastPapersAnnotationsRouteImport } from './routes/api/past-papers/annotations'
import { Route as ApiFeedbackSuspensionRouteImport } from './routes/api/feedback/suspension'
import { Route as ApiFeedbackReportsRouteImport } from './routes/api/feedback/reports'
import { Route as ApiDesktopReleaseRouteImport } from './routes/api/desktop/release'
import { Route as ApiDesktopLoginTokenRouteImport } from './routes/api/desktop/login-token'
import { Route as ApiDesktopBootstrapRouteImport } from './routes/api/desktop/bootstrap'
import { Route as ApiCronRetentionRouteImport } from './routes/api/cron/retention'
import { Route as ApiClassroomSyncSessionsRouteImport } from './routes/api/classroom/sync-sessions'
import { Route as ApiClassroomDataRouteImport } from './routes/api/classroom/data'
import { Route as ApiChangelogBumpsRouteImport } from './routes/api/changelog/bumps'
import { Route as ApiCalendarUnlinkRouteImport } from './routes/api/calendar/unlink'
import { Route as ApiCalendarEventsRouteImport } from './routes/api/calendar/events'
import { Route as ApiCalendarEventRouteImport } from './routes/api/calendar/event'
import { Route as ApiCalendarCreateRouteImport } from './routes/api/calendar/create'
import { Route as ApiCalendarCalendarsRouteImport } from './routes/api/calendar/calendars'
import { Route as ApiBillingStatusRouteImport } from './routes/api/billing/status'
import { Route as ApiBillingPortalRouteImport } from './routes/api/billing/portal'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api/billing/checkout'
import { Route as ApiAuthTokenLoginRouteImport } from './routes/api/auth/token-login'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthForgotPasswordRouteImport } from './routes/api/auth/forgot-password'
import { Route as ApiAssistantStateRouteImport } from './routes/api/assistant/state'
import { Route as ApiAssistantSkillWriterRouteImport } from './routes/api/assistant/skill-writer'
import { Route as ApiAssistantProvidersRouteImport } from './routes/api/assistant/providers'
import { Route as ApiAssistantContextRouteImport } from './routes/api/assistant/context'
import { Route as ApiAssistantChatRouteImport } from './routes/api/assistant/chat'
import { Route as ApiAppSessionRouteImport } from './routes/api/app/session'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminGithubIssuesRouteImport } from './routes/api/admin/github-issues'
import { Route as ApiAdminFeedbackRouteImport } from './routes/api/admin/feedback'
import { Route as ApiClassroomSyncSessionsSessionIdRouteImport } from './routes/api/classroom/sync-sessions/$sessionId'
import { Route as ApiClassroomSyncSessionsSessionIdUploadRouteImport } from './routes/api/classroom/sync-sessions/$sessionId/upload'

const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOpenIndexRoute = AppOpenIndexRouteImport.update({
  id: '/app-open/',
  path: '/app-open/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOpenRoute = AppOpenRouteImport.update({
  id: '/app/open',
  path: '/app/open',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadinessRoute = ApiReadinessRouteImport.update({
  id: '/api/readiness',
  path: '/api/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserThemeBuilderRoute = ApiUserThemeBuilderRouteImport.update({
  id: '/api/user/theme-builder',
  path: '/api/user/theme-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserProfileImageRoute = ApiUserProfileImageRouteImport.update({
  id: '/api/user/profile-image',
  path: '/api/user/profile-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserPreferencesRoute = ApiUserPreferencesRouteImport.update({
  id: '/api/user/preferences',
  path: '/api/user/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserNotificationsRoute = ApiUserNotificationsRouteImport.update({
  id: '/api/user/notifications',
  path: '/api/user/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserLocalCalendarRoute = ApiUserLocalCalendarRouteImport.update({
  id: '/api/user/local-calendar',
  path: '/api/user/local-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserExportRoute = ApiUserExportRouteImport.update({
  id: '/api/user/export',
  path: '/api/user/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserAccountRoute = ApiUserAccountRouteImport.update({
  id: '/api/user/account',
  path: '/api/user/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThemesExploreRoute = ApiThemesExploreRouteImport.update({
  id: '/api/themes/explore',
  path: '/api/themes/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyWorkshopRoute = ApiStudyWorkshopRouteImport.update({
  id: '/api/study/workshop',
  path: '/api/study/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyUndoRoute = ApiStudyUndoRouteImport.update({
  id: '/api/study/undo',
  path: '/api/study/undo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyTrialRoute = ApiStudyTrialRouteImport.update({
  id: '/api/study/trial',
  path: '/api/study/trial',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudySyncRoute = ApiStudySyncRouteImport.update({
  id: '/api/study/sync',
  path: '/api/study/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudySessionsRoute = ApiStudySessionsRouteImport.update({
  id: '/api/study/sessions',
  path: '/api/study/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyReviewsRoute = ApiStudyReviewsRouteImport.update({
  id: '/api/study/reviews',
  path: '/api/study/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyQueueRoute = ApiStudyQueueRouteImport.update({
  id: '/api/study/queue',
  path: '/api/study/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyPreferencesRoute = ApiStudyPreferencesRouteImport.update({
  id: '/api/study/preferences',
  path: '/api/study/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyPlanningRoute = ApiStudyPlanningRouteImport.update({
  id: '/api/study/planning',
  path: '/api/study/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyNotesRoute = ApiStudyNotesRouteImport.update({
  id: '/api/study/notes',
  path: '/api/study/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyMigrateRoute = ApiStudyMigrateRouteImport.update({
  id: '/api/study/migrate',
  path: '/api/study/migrate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyMediaRoute = ApiStudyMediaRouteImport.update({
  id: '/api/study/media',
  path: '/api/study/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyImportRoute = ApiStudyImportRouteImport.update({
  id: '/api/study/import',
  path: '/api/study/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyFlashcardsRoute = ApiStudyFlashcardsRouteImport.update({
  id: '/api/study/flashcards',
  path: '/api/study/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyExportRoute = ApiStudyExportRouteImport.update({
  id: '/api/study/export',
  path: '/api/study/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyDecksRoute = ApiStudyDecksRouteImport.update({
  id: '/api/study/decks',
  path: '/api/study/decks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyCutoverRoute = ApiStudyCutoverRouteImport.update({
  id: '/api/study/cutover',
  path: '/api/study/cutover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyBrowserRoute = ApiStudyBrowserRouteImport.update({
  id: '/api/study/browser',
  path: '/api/study/browser',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyBootstrapRoute = ApiStudyBootstrapRouteImport.update({
  id: '/api/study/bootstrap',
  path: '/api/study/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyAnalyticsRoute = ApiStudyAnalyticsRouteImport.update({
  id: '/api/study/analytics',
  path: '/api/study/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsPdfRoute = ApiReportsPdfRouteImport.update({
  id: '/api/reports/pdf',
  path: '/api/reports/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsAnnotationsRoute = ApiReportsAnnotationsRouteImport.update({
  id: '/api/reports/annotations',
  path: '/api/reports/annotations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalSyncRoute = ApiPortalSyncRouteImport.update({
  id: '/api/portal/sync',
  path: '/api/portal/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalLoginRoute = ApiPortalLoginRouteImport.update({
  id: '/api/portal/login',
  path: '/api/portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalDataRoute = ApiPortalDataRouteImport.update({
  id: '/api/portal/data',
  path: '/api/portal/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalAccountRoute = ApiPortalAccountRouteImport.update({
  id: '/api/portal/account',
  path: '/api/portal/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPastPapersShareRoute = ApiPastPapersShareRouteImport.update({
  id: '/api/past-papers/share',
  path: '/api/past-papers/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPastPapersSavesRoute = ApiPastPapersSavesRouteImport.update({
  id: '/api/past-papers/saves',
  path: '/api/past-papers/saves',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPastPapersReindexRoute = ApiPastPapersReindexRouteImport.update({
  id: '/api/past-papers/reindex',
  path: '/api/past-papers/reindex',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPastPapersPreferencesRoute =
  ApiPastPapersPreferencesRouteImport.update({
    id: '/api/past-papers/preferences',
    path: '/api/past-papers/preferences',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPastPapersPdfRoute = ApiPastPapersPdfRouteImport.update({
  id: '/api/past-papers/pdf',
  path: '/api/past-papers/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPastPapersLibraryRoute = ApiPastPapersLibraryRouteImport.update({
  id: '/api/past-papers/library',
  path: '/api/past-papers/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPastPapersBrowseRoute = ApiPastPapersBrowseRouteImport.update({
  id: '/api/past-papers/browse',
  path: '/api/past-papers/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPastPapersAttemptsRoute = ApiPastPapersAttemptsRouteImport.update({
  id: '/api/past-papers/attempts',
  path: '/api/past-papers/attempts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPastPapersAnnotationsRoute =
  ApiPastPapersAnnotationsRouteImport.update({
    id: '/api/past-papers/annotations',
    path: '/api/past-papers/annotations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFeedbackSuspensionRoute = ApiFeedbackSuspensionRouteImport.update({
  id: '/api/feedback/suspension',
  path: '/api/feedback/suspension',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackReportsRoute = ApiFeedbackReportsRouteImport.update({
  id: '/api/feedback/reports',
  path: '/api/feedback/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDesktopReleaseRoute = ApiDesktopReleaseRouteImport.update({
  id: '/api/desktop/release',
  path: '/api/desktop/release',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDesktopLoginTokenRoute = ApiDesktopLoginTokenRouteImport.update({
  id: '/api/desktop/login-token',
  path: '/api/desktop/login-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDesktopBootstrapRoute = ApiDesktopBootstrapRouteImport.update({
  id: '/api/desktop/bootstrap',
  path: '/api/desktop/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRetentionRoute = ApiCronRetentionRouteImport.update({
  id: '/api/cron/retention',
  path: '/api/cron/retention',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClassroomSyncSessionsRoute =
  ApiClassroomSyncSessionsRouteImport.update({
    id: '/api/classroom/sync-sessions',
    path: '/api/classroom/sync-sessions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiClassroomDataRoute = ApiClassroomDataRouteImport.update({
  id: '/api/classroom/data',
  path: '/api/classroom/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChangelogBumpsRoute = ApiChangelogBumpsRouteImport.update({
  id: '/api/changelog/bumps',
  path: '/api/changelog/bumps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarUnlinkRoute = ApiCalendarUnlinkRouteImport.update({
  id: '/api/calendar/unlink',
  path: '/api/calendar/unlink',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarEventsRoute = ApiCalendarEventsRouteImport.update({
  id: '/api/calendar/events',
  path: '/api/calendar/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarEventRoute = ApiCalendarEventRouteImport.update({
  id: '/api/calendar/event',
  path: '/api/calendar/event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarCreateRoute = ApiCalendarCreateRouteImport.update({
  id: '/api/calendar/create',
  path: '/api/calendar/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarCalendarsRoute = ApiCalendarCalendarsRouteImport.update({
  id: '/api/calendar/calendars',
  path: '/api/calendar/calendars',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingStatusRoute = ApiBillingStatusRouteImport.update({
  id: '/api/billing/status',
  path: '/api/billing/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPortalRoute = ApiBillingPortalRouteImport.update({
  id: '/api/billing/portal',
  path: '/api/billing/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthTokenLoginRoute = ApiAuthTokenLoginRouteImport.update({
  id: '/api/auth/token-login',
  path: '/api/auth/token-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthForgotPasswordRoute = ApiAuthForgotPasswordRouteImport.update({
  id: '/api/auth/forgot-password',
  path: '/api/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantStateRoute = ApiAssistantStateRouteImport.update({
  id: '/api/assistant/state',
  path: '/api/assistant/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantSkillWriterRoute = ApiAssistantSkillWriterRouteImport.update({
  id: '/api/assistant/skill-writer',
  path: '/api/assistant/skill-writer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantProvidersRoute = ApiAssistantProvidersRouteImport.update({
  id: '/api/assistant/providers',
  path: '/api/assistant/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantContextRoute = ApiAssistantContextRouteImport.update({
  id: '/api/assistant/context',
  path: '/api/assistant/context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantChatRoute = ApiAssistantChatRouteImport.update({
  id: '/api/assistant/chat',
  path: '/api/assistant/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppSessionRoute = ApiAppSessionRouteImport.update({
  id: '/api/app/session',
  path: '/api/app/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminGithubIssuesRoute = ApiAdminGithubIssuesRouteImport.update({
  id: '/api/admin/github-issues',
  path: '/api/admin/github-issues',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFeedbackRoute = ApiAdminFeedbackRouteImport.update({
  id: '/api/admin/feedback',
  path: '/api/admin/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClassroomSyncSessionsSessionIdRoute =
  ApiClassroomSyncSessionsSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => ApiClassroomSyncSessionsRoute,
  } as any)
const ApiClassroomSyncSessionsSessionIdUploadRoute =
  ApiClassroomSyncSessionsSessionIdUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => ApiClassroomSyncSessionsSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/updates': typeof UpdatesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/readiness': typeof ApiReadinessRoute
  '/app/open': typeof AppOpenRoute
  '/app-open/': typeof AppOpenIndexRoute
  '/api/admin/feedback': typeof ApiAdminFeedbackRoute
  '/api/admin/github-issues': typeof ApiAdminGithubIssuesRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/app/session': typeof ApiAppSessionRoute
  '/api/assistant/chat': typeof ApiAssistantChatRoute
  '/api/assistant/context': typeof ApiAssistantContextRoute
  '/api/assistant/providers': typeof ApiAssistantProvidersRoute
  '/api/assistant/skill-writer': typeof ApiAssistantSkillWriterRoute
  '/api/assistant/state': typeof ApiAssistantStateRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/token-login': typeof ApiAuthTokenLoginRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/status': typeof ApiBillingStatusRoute
  '/api/calendar/calendars': typeof ApiCalendarCalendarsRoute
  '/api/calendar/create': typeof ApiCalendarCreateRoute
  '/api/calendar/event': typeof ApiCalendarEventRoute
  '/api/calendar/events': typeof ApiCalendarEventsRoute
  '/api/calendar/unlink': typeof ApiCalendarUnlinkRoute
  '/api/changelog/bumps': typeof ApiChangelogBumpsRoute
  '/api/classroom/data': typeof ApiClassroomDataRoute
  '/api/classroom/sync-sessions': typeof ApiClassroomSyncSessionsRouteWithChildren
  '/api/cron/retention': typeof ApiCronRetentionRoute
  '/api/desktop/bootstrap': typeof ApiDesktopBootstrapRoute
  '/api/desktop/login-token': typeof ApiDesktopLoginTokenRoute
  '/api/desktop/release': typeof ApiDesktopReleaseRoute
  '/api/feedback/reports': typeof ApiFeedbackReportsRoute
  '/api/feedback/suspension': typeof ApiFeedbackSuspensionRoute
  '/api/past-papers/annotations': typeof ApiPastPapersAnnotationsRoute
  '/api/past-papers/attempts': typeof ApiPastPapersAttemptsRoute
  '/api/past-papers/browse': typeof ApiPastPapersBrowseRoute
  '/api/past-papers/library': typeof ApiPastPapersLibraryRoute
  '/api/past-papers/pdf': typeof ApiPastPapersPdfRoute
  '/api/past-papers/preferences': typeof ApiPastPapersPreferencesRoute
  '/api/past-papers/reindex': typeof ApiPastPapersReindexRoute
  '/api/past-papers/saves': typeof ApiPastPapersSavesRoute
  '/api/past-papers/share': typeof ApiPastPapersShareRoute
  '/api/portal/account': typeof ApiPortalAccountRoute
  '/api/portal/data': typeof ApiPortalDataRoute
  '/api/portal/login': typeof ApiPortalLoginRoute
  '/api/portal/sync': typeof ApiPortalSyncRoute
  '/api/reports/annotations': typeof ApiReportsAnnotationsRoute
  '/api/reports/pdf': typeof ApiReportsPdfRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/study/analytics': typeof ApiStudyAnalyticsRoute
  '/api/study/bootstrap': typeof ApiStudyBootstrapRoute
  '/api/study/browser': typeof ApiStudyBrowserRoute
  '/api/study/cutover': typeof ApiStudyCutoverRoute
  '/api/study/decks': typeof ApiStudyDecksRoute
  '/api/study/export': typeof ApiStudyExportRoute
  '/api/study/flashcards': typeof ApiStudyFlashcardsRoute
  '/api/study/import': typeof ApiStudyImportRoute
  '/api/study/media': typeof ApiStudyMediaRoute
  '/api/study/migrate': typeof ApiStudyMigrateRoute
  '/api/study/notes': typeof ApiStudyNotesRoute
  '/api/study/planning': typeof ApiStudyPlanningRoute
  '/api/study/preferences': typeof ApiStudyPreferencesRoute
  '/api/study/queue': typeof ApiStudyQueueRoute
  '/api/study/reviews': typeof ApiStudyReviewsRoute
  '/api/study/sessions': typeof ApiStudySessionsRoute
  '/api/study/sync': typeof ApiStudySyncRoute
  '/api/study/trial': typeof ApiStudyTrialRoute
  '/api/study/undo': typeof ApiStudyUndoRoute
  '/api/study/workshop': typeof ApiStudyWorkshopRoute
  '/api/themes/explore': typeof ApiThemesExploreRoute
  '/api/user/account': typeof ApiUserAccountRoute
  '/api/user/export': typeof ApiUserExportRoute
  '/api/user/local-calendar': typeof ApiUserLocalCalendarRoute
  '/api/user/notifications': typeof ApiUserNotificationsRoute
  '/api/user/preferences': typeof ApiUserPreferencesRoute
  '/api/user/profile-image': typeof ApiUserProfileImageRoute
  '/api/user/theme-builder': typeof ApiUserThemeBuilderRoute
  '/api/classroom/sync-sessions/$sessionId': typeof ApiClassroomSyncSessionsSessionIdRouteWithChildren
  '/api/classroom/sync-sessions/$sessionId/upload': typeof ApiClassroomSyncSessionsSessionIdUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/updates': typeof UpdatesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/readiness': typeof ApiReadinessRoute
  '/app/open': typeof AppOpenRoute
  '/app-open': typeof AppOpenIndexRoute
  '/api/admin/feedback': typeof ApiAdminFeedbackRoute
  '/api/admin/github-issues': typeof ApiAdminGithubIssuesRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/app/session': typeof ApiAppSessionRoute
  '/api/assistant/chat': typeof ApiAssistantChatRoute
  '/api/assistant/context': typeof ApiAssistantContextRoute
  '/api/assistant/providers': typeof ApiAssistantProvidersRoute
  '/api/assistant/skill-writer': typeof ApiAssistantSkillWriterRoute
  '/api/assistant/state': typeof ApiAssistantStateRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/token-login': typeof ApiAuthTokenLoginRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/status': typeof ApiBillingStatusRoute
  '/api/calendar/calendars': typeof ApiCalendarCalendarsRoute
  '/api/calendar/create': typeof ApiCalendarCreateRoute
  '/api/calendar/event': typeof ApiCalendarEventRoute
  '/api/calendar/events': typeof ApiCalendarEventsRoute
  '/api/calendar/unlink': typeof ApiCalendarUnlinkRoute
  '/api/changelog/bumps': typeof ApiChangelogBumpsRoute
  '/api/classroom/data': typeof ApiClassroomDataRoute
  '/api/classroom/sync-sessions': typeof ApiClassroomSyncSessionsRouteWithChildren
  '/api/cron/retention': typeof ApiCronRetentionRoute
  '/api/desktop/bootstrap': typeof ApiDesktopBootstrapRoute
  '/api/desktop/login-token': typeof ApiDesktopLoginTokenRoute
  '/api/desktop/release': typeof ApiDesktopReleaseRoute
  '/api/feedback/reports': typeof ApiFeedbackReportsRoute
  '/api/feedback/suspension': typeof ApiFeedbackSuspensionRoute
  '/api/past-papers/annotations': typeof ApiPastPapersAnnotationsRoute
  '/api/past-papers/attempts': typeof ApiPastPapersAttemptsRoute
  '/api/past-papers/browse': typeof ApiPastPapersBrowseRoute
  '/api/past-papers/library': typeof ApiPastPapersLibraryRoute
  '/api/past-papers/pdf': typeof ApiPastPapersPdfRoute
  '/api/past-papers/preferences': typeof ApiPastPapersPreferencesRoute
  '/api/past-papers/reindex': typeof ApiPastPapersReindexRoute
  '/api/past-papers/saves': typeof ApiPastPapersSavesRoute
  '/api/past-papers/share': typeof ApiPastPapersShareRoute
  '/api/portal/account': typeof ApiPortalAccountRoute
  '/api/portal/data': typeof ApiPortalDataRoute
  '/api/portal/login': typeof ApiPortalLoginRoute
  '/api/portal/sync': typeof ApiPortalSyncRoute
  '/api/reports/annotations': typeof ApiReportsAnnotationsRoute
  '/api/reports/pdf': typeof ApiReportsPdfRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/study/analytics': typeof ApiStudyAnalyticsRoute
  '/api/study/bootstrap': typeof ApiStudyBootstrapRoute
  '/api/study/browser': typeof ApiStudyBrowserRoute
  '/api/study/cutover': typeof ApiStudyCutoverRoute
  '/api/study/decks': typeof ApiStudyDecksRoute
  '/api/study/export': typeof ApiStudyExportRoute
  '/api/study/flashcards': typeof ApiStudyFlashcardsRoute
  '/api/study/import': typeof ApiStudyImportRoute
  '/api/study/media': typeof ApiStudyMediaRoute
  '/api/study/migrate': typeof ApiStudyMigrateRoute
  '/api/study/notes': typeof ApiStudyNotesRoute
  '/api/study/planning': typeof ApiStudyPlanningRoute
  '/api/study/preferences': typeof ApiStudyPreferencesRoute
  '/api/study/queue': typeof ApiStudyQueueRoute
  '/api/study/reviews': typeof ApiStudyReviewsRoute
  '/api/study/sessions': typeof ApiStudySessionsRoute
  '/api/study/sync': typeof ApiStudySyncRoute
  '/api/study/trial': typeof ApiStudyTrialRoute
  '/api/study/undo': typeof ApiStudyUndoRoute
  '/api/study/workshop': typeof ApiStudyWorkshopRoute
  '/api/themes/explore': typeof ApiThemesExploreRoute
  '/api/user/account': typeof ApiUserAccountRoute
  '/api/user/export': typeof ApiUserExportRoute
  '/api/user/local-calendar': typeof ApiUserLocalCalendarRoute
  '/api/user/notifications': typeof ApiUserNotificationsRoute
  '/api/user/preferences': typeof ApiUserPreferencesRoute
  '/api/user/profile-image': typeof ApiUserProfileImageRoute
  '/api/user/theme-builder': typeof ApiUserThemeBuilderRoute
  '/api/classroom/sync-sessions/$sessionId': typeof ApiClassroomSyncSessionsSessionIdRouteWithChildren
  '/api/classroom/sync-sessions/$sessionId/upload': typeof ApiClassroomSyncSessionsSessionIdUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/updates': typeof UpdatesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/readiness': typeof ApiReadinessRoute
  '/app/open': typeof AppOpenRoute
  '/app-open/': typeof AppOpenIndexRoute
  '/api/admin/feedback': typeof ApiAdminFeedbackRoute
  '/api/admin/github-issues': typeof ApiAdminGithubIssuesRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/app/session': typeof ApiAppSessionRoute
  '/api/assistant/chat': typeof ApiAssistantChatRoute
  '/api/assistant/context': typeof ApiAssistantContextRoute
  '/api/assistant/providers': typeof ApiAssistantProvidersRoute
  '/api/assistant/skill-writer': typeof ApiAssistantSkillWriterRoute
  '/api/assistant/state': typeof ApiAssistantStateRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/token-login': typeof ApiAuthTokenLoginRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/status': typeof ApiBillingStatusRoute
  '/api/calendar/calendars': typeof ApiCalendarCalendarsRoute
  '/api/calendar/create': typeof ApiCalendarCreateRoute
  '/api/calendar/event': typeof ApiCalendarEventRoute
  '/api/calendar/events': typeof ApiCalendarEventsRoute
  '/api/calendar/unlink': typeof ApiCalendarUnlinkRoute
  '/api/changelog/bumps': typeof ApiChangelogBumpsRoute
  '/api/classroom/data': typeof ApiClassroomDataRoute
  '/api/classroom/sync-sessions': typeof ApiClassroomSyncSessionsRouteWithChildren
  '/api/cron/retention': typeof ApiCronRetentionRoute
  '/api/desktop/bootstrap': typeof ApiDesktopBootstrapRoute
  '/api/desktop/login-token': typeof ApiDesktopLoginTokenRoute
  '/api/desktop/release': typeof ApiDesktopReleaseRoute
  '/api/feedback/reports': typeof ApiFeedbackReportsRoute
  '/api/feedback/suspension': typeof ApiFeedbackSuspensionRoute
  '/api/past-papers/annotations': typeof ApiPastPapersAnnotationsRoute
  '/api/past-papers/attempts': typeof ApiPastPapersAttemptsRoute
  '/api/past-papers/browse': typeof ApiPastPapersBrowseRoute
  '/api/past-papers/library': typeof ApiPastPapersLibraryRoute
  '/api/past-papers/pdf': typeof ApiPastPapersPdfRoute
  '/api/past-papers/preferences': typeof ApiPastPapersPreferencesRoute
  '/api/past-papers/reindex': typeof ApiPastPapersReindexRoute
  '/api/past-papers/saves': typeof ApiPastPapersSavesRoute
  '/api/past-papers/share': typeof ApiPastPapersShareRoute
  '/api/portal/account': typeof ApiPortalAccountRoute
  '/api/portal/data': typeof ApiPortalDataRoute
  '/api/portal/login': typeof ApiPortalLoginRoute
  '/api/portal/sync': typeof ApiPortalSyncRoute
  '/api/reports/annotations': typeof ApiReportsAnnotationsRoute
  '/api/reports/pdf': typeof ApiReportsPdfRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/study/analytics': typeof ApiStudyAnalyticsRoute
  '/api/study/bootstrap': typeof ApiStudyBootstrapRoute
  '/api/study/browser': typeof ApiStudyBrowserRoute
  '/api/study/cutover': typeof ApiStudyCutoverRoute
  '/api/study/decks': typeof ApiStudyDecksRoute
  '/api/study/export': typeof ApiStudyExportRoute
  '/api/study/flashcards': typeof ApiStudyFlashcardsRoute
  '/api/study/import': typeof ApiStudyImportRoute
  '/api/study/media': typeof ApiStudyMediaRoute
  '/api/study/migrate': typeof ApiStudyMigrateRoute
  '/api/study/notes': typeof ApiStudyNotesRoute
  '/api/study/planning': typeof ApiStudyPlanningRoute
  '/api/study/preferences': typeof ApiStudyPreferencesRoute
  '/api/study/queue': typeof ApiStudyQueueRoute
  '/api/study/reviews': typeof ApiStudyReviewsRoute
  '/api/study/sessions': typeof ApiStudySessionsRoute
  '/api/study/sync': typeof ApiStudySyncRoute
  '/api/study/trial': typeof ApiStudyTrialRoute
  '/api/study/undo': typeof ApiStudyUndoRoute
  '/api/study/workshop': typeof ApiStudyWorkshopRoute
  '/api/themes/explore': typeof ApiThemesExploreRoute
  '/api/user/account': typeof ApiUserAccountRoute
  '/api/user/export': typeof ApiUserExportRoute
  '/api/user/local-calendar': typeof ApiUserLocalCalendarRoute
  '/api/user/notifications': typeof ApiUserNotificationsRoute
  '/api/user/preferences': typeof ApiUserPreferencesRoute
  '/api/user/profile-image': typeof ApiUserProfileImageRoute
  '/api/user/theme-builder': typeof ApiUserThemeBuilderRoute
  '/api/classroom/sync-sessions/$sessionId': typeof ApiClassroomSyncSessionsSessionIdRouteWithChildren
  '/api/classroom/sync-sessions/$sessionId/upload': typeof ApiClassroomSyncSessionsSessionIdUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/changelog'
    | '/dashboard'
    | '/download'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/updates'
    | '/api/health'
    | '/api/readiness'
    | '/app/open'
    | '/app-open/'
    | '/api/admin/feedback'
    | '/api/admin/github-issues'
    | '/api/admin/users'
    | '/api/app/session'
    | '/api/assistant/chat'
    | '/api/assistant/context'
    | '/api/assistant/providers'
    | '/api/assistant/skill-writer'
    | '/api/assistant/state'
    | '/api/auth/forgot-password'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/auth/token-login'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/billing/status'
    | '/api/calendar/calendars'
    | '/api/calendar/create'
    | '/api/calendar/event'
    | '/api/calendar/events'
    | '/api/calendar/unlink'
    | '/api/changelog/bumps'
    | '/api/classroom/data'
    | '/api/classroom/sync-sessions'
    | '/api/cron/retention'
    | '/api/desktop/bootstrap'
    | '/api/desktop/login-token'
    | '/api/desktop/release'
    | '/api/feedback/reports'
    | '/api/feedback/suspension'
    | '/api/past-papers/annotations'
    | '/api/past-papers/attempts'
    | '/api/past-papers/browse'
    | '/api/past-papers/library'
    | '/api/past-papers/pdf'
    | '/api/past-papers/preferences'
    | '/api/past-papers/reindex'
    | '/api/past-papers/saves'
    | '/api/past-papers/share'
    | '/api/portal/account'
    | '/api/portal/data'
    | '/api/portal/login'
    | '/api/portal/sync'
    | '/api/reports/annotations'
    | '/api/reports/pdf'
    | '/api/stripe/webhook'
    | '/api/study/analytics'
    | '/api/study/bootstrap'
    | '/api/study/browser'
    | '/api/study/cutover'
    | '/api/study/decks'
    | '/api/study/export'
    | '/api/study/flashcards'
    | '/api/study/import'
    | '/api/study/media'
    | '/api/study/migrate'
    | '/api/study/notes'
    | '/api/study/planning'
    | '/api/study/preferences'
    | '/api/study/queue'
    | '/api/study/reviews'
    | '/api/study/sessions'
    | '/api/study/sync'
    | '/api/study/trial'
    | '/api/study/undo'
    | '/api/study/workshop'
    | '/api/themes/explore'
    | '/api/user/account'
    | '/api/user/export'
    | '/api/user/local-calendar'
    | '/api/user/notifications'
    | '/api/user/preferences'
    | '/api/user/profile-image'
    | '/api/user/theme-builder'
    | '/api/classroom/sync-sessions/$sessionId'
    | '/api/classroom/sync-sessions/$sessionId/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/changelog'
    | '/dashboard'
    | '/download'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/updates'
    | '/api/health'
    | '/api/readiness'
    | '/app/open'
    | '/app-open'
    | '/api/admin/feedback'
    | '/api/admin/github-issues'
    | '/api/admin/users'
    | '/api/app/session'
    | '/api/assistant/chat'
    | '/api/assistant/context'
    | '/api/assistant/providers'
    | '/api/assistant/skill-writer'
    | '/api/assistant/state'
    | '/api/auth/forgot-password'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/auth/token-login'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/billing/status'
    | '/api/calendar/calendars'
    | '/api/calendar/create'
    | '/api/calendar/event'
    | '/api/calendar/events'
    | '/api/calendar/unlink'
    | '/api/changelog/bumps'
    | '/api/classroom/data'
    | '/api/classroom/sync-sessions'
    | '/api/cron/retention'
    | '/api/desktop/bootstrap'
    | '/api/desktop/login-token'
    | '/api/desktop/release'
    | '/api/feedback/reports'
    | '/api/feedback/suspension'
    | '/api/past-papers/annotations'
    | '/api/past-papers/attempts'
    | '/api/past-papers/browse'
    | '/api/past-papers/library'
    | '/api/past-papers/pdf'
    | '/api/past-papers/preferences'
    | '/api/past-papers/reindex'
    | '/api/past-papers/saves'
    | '/api/past-papers/share'
    | '/api/portal/account'
    | '/api/portal/data'
    | '/api/portal/login'
    | '/api/portal/sync'
    | '/api/reports/annotations'
    | '/api/reports/pdf'
    | '/api/stripe/webhook'
    | '/api/study/analytics'
    | '/api/study/bootstrap'
    | '/api/study/browser'
    | '/api/study/cutover'
    | '/api/study/decks'
    | '/api/study/export'
    | '/api/study/flashcards'
    | '/api/study/import'
    | '/api/study/media'
    | '/api/study/migrate'
    | '/api/study/notes'
    | '/api/study/planning'
    | '/api/study/preferences'
    | '/api/study/queue'
    | '/api/study/reviews'
    | '/api/study/sessions'
    | '/api/study/sync'
    | '/api/study/trial'
    | '/api/study/undo'
    | '/api/study/workshop'
    | '/api/themes/explore'
    | '/api/user/account'
    | '/api/user/export'
    | '/api/user/local-calendar'
    | '/api/user/notifications'
    | '/api/user/preferences'
    | '/api/user/profile-image'
    | '/api/user/theme-builder'
    | '/api/classroom/sync-sessions/$sessionId'
    | '/api/classroom/sync-sessions/$sessionId/upload'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/changelog'
    | '/dashboard'
    | '/download'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/updates'
    | '/api/health'
    | '/api/readiness'
    | '/app/open'
    | '/app-open/'
    | '/api/admin/feedback'
    | '/api/admin/github-issues'
    | '/api/admin/users'
    | '/api/app/session'
    | '/api/assistant/chat'
    | '/api/assistant/context'
    | '/api/assistant/providers'
    | '/api/assistant/skill-writer'
    | '/api/assistant/state'
    | '/api/auth/forgot-password'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/auth/token-login'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/billing/status'
    | '/api/calendar/calendars'
    | '/api/calendar/create'
    | '/api/calendar/event'
    | '/api/calendar/events'
    | '/api/calendar/unlink'
    | '/api/changelog/bumps'
    | '/api/classroom/data'
    | '/api/classroom/sync-sessions'
    | '/api/cron/retention'
    | '/api/desktop/bootstrap'
    | '/api/desktop/login-token'
    | '/api/desktop/release'
    | '/api/feedback/reports'
    | '/api/feedback/suspension'
    | '/api/past-papers/annotations'
    | '/api/past-papers/attempts'
    | '/api/past-papers/browse'
    | '/api/past-papers/library'
    | '/api/past-papers/pdf'
    | '/api/past-papers/preferences'
    | '/api/past-papers/reindex'
    | '/api/past-papers/saves'
    | '/api/past-papers/share'
    | '/api/portal/account'
    | '/api/portal/data'
    | '/api/portal/login'
    | '/api/portal/sync'
    | '/api/reports/annotations'
    | '/api/reports/pdf'
    | '/api/stripe/webhook'
    | '/api/study/analytics'
    | '/api/study/bootstrap'
    | '/api/study/browser'
    | '/api/study/cutover'
    | '/api/study/decks'
    | '/api/study/export'
    | '/api/study/flashcards'
    | '/api/study/import'
    | '/api/study/media'
    | '/api/study/migrate'
    | '/api/study/notes'
    | '/api/study/planning'
    | '/api/study/preferences'
    | '/api/study/queue'
    | '/api/study/reviews'
    | '/api/study/sessions'
    | '/api/study/sync'
    | '/api/study/trial'
    | '/api/study/undo'
    | '/api/study/workshop'
    | '/api/themes/explore'
    | '/api/user/account'
    | '/api/user/export'
    | '/api/user/local-calendar'
    | '/api/user/notifications'
    | '/api/user/preferences'
    | '/api/user/profile-image'
    | '/api/user/theme-builder'
    | '/api/classroom/sync-sessions/$sessionId'
    | '/api/classroom/sync-sessions/$sessionId/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  ChangelogRoute: typeof ChangelogRoute
  DashboardRoute: typeof DashboardRoute
  DownloadRoute: typeof DownloadRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  UpdatesRoute: typeof UpdatesRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiReadinessRoute: typeof ApiReadinessRoute
  AppOpenRoute: typeof AppOpenRoute
  AppOpenIndexRoute: typeof AppOpenIndexRoute
  ApiAdminFeedbackRoute: typeof ApiAdminFeedbackRoute
  ApiAdminGithubIssuesRoute: typeof ApiAdminGithubIssuesRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAppSessionRoute: typeof ApiAppSessionRoute
  ApiAssistantChatRoute: typeof ApiAssistantChatRoute
  ApiAssistantContextRoute: typeof ApiAssistantContextRoute
  ApiAssistantProvidersRoute: typeof ApiAssistantProvidersRoute
  ApiAssistantSkillWriterRoute: typeof ApiAssistantSkillWriterRoute
  ApiAssistantStateRoute: typeof ApiAssistantStateRoute
  ApiAuthForgotPasswordRoute: typeof ApiAuthForgotPasswordRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiAuthTokenLoginRoute: typeof ApiAuthTokenLoginRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingPortalRoute: typeof ApiBillingPortalRoute
  ApiBillingStatusRoute: typeof ApiBillingStatusRoute
  ApiCalendarCalendarsRoute: typeof ApiCalendarCalendarsRoute
  ApiCalendarCreateRoute: typeof ApiCalendarCreateRoute
  ApiCalendarEventRoute: typeof ApiCalendarEventRoute
  ApiCalendarEventsRoute: typeof ApiCalendarEventsRoute
  ApiCalendarUnlinkRoute: typeof ApiCalendarUnlinkRoute
  ApiChangelogBumpsRoute: typeof ApiChangelogBumpsRoute
  ApiClassroomDataRoute: typeof ApiClassroomDataRoute
  ApiClassroomSyncSessionsRoute: typeof ApiClassroomSyncSessionsRouteWithChildren
  ApiCronRetentionRoute: typeof ApiCronRetentionRoute
  ApiDesktopBootstrapRoute: typeof ApiDesktopBootstrapRoute
  ApiDesktopLoginTokenRoute: typeof ApiDesktopLoginTokenRoute
  ApiDesktopReleaseRoute: typeof ApiDesktopReleaseRoute
  ApiFeedbackReportsRoute: typeof ApiFeedbackReportsRoute
  ApiFeedbackSuspensionRoute: typeof ApiFeedbackSuspensionRoute
  ApiPastPapersAnnotationsRoute: typeof ApiPastPapersAnnotationsRoute
  ApiPastPapersAttemptsRoute: typeof ApiPastPapersAttemptsRoute
  ApiPastPapersBrowseRoute: typeof ApiPastPapersBrowseRoute
  ApiPastPapersLibraryRoute: typeof ApiPastPapersLibraryRoute
  ApiPastPapersPdfRoute: typeof ApiPastPapersPdfRoute
  ApiPastPapersPreferencesRoute: typeof ApiPastPapersPreferencesRoute
  ApiPastPapersReindexRoute: typeof ApiPastPapersReindexRoute
  ApiPastPapersSavesRoute: typeof ApiPastPapersSavesRoute
  ApiPastPapersShareRoute: typeof ApiPastPapersShareRoute
  ApiPortalAccountRoute: typeof ApiPortalAccountRoute
  ApiPortalDataRoute: typeof ApiPortalDataRoute
  ApiPortalLoginRoute: typeof ApiPortalLoginRoute
  ApiPortalSyncRoute: typeof ApiPortalSyncRoute
  ApiReportsAnnotationsRoute: typeof ApiReportsAnnotationsRoute
  ApiReportsPdfRoute: typeof ApiReportsPdfRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiStudyAnalyticsRoute: typeof ApiStudyAnalyticsRoute
  ApiStudyBootstrapRoute: typeof ApiStudyBootstrapRoute
  ApiStudyBrowserRoute: typeof ApiStudyBrowserRoute
  ApiStudyCutoverRoute: typeof ApiStudyCutoverRoute
  ApiStudyDecksRoute: typeof ApiStudyDecksRoute
  ApiStudyExportRoute: typeof ApiStudyExportRoute
  ApiStudyFlashcardsRoute: typeof ApiStudyFlashcardsRoute
  ApiStudyImportRoute: typeof ApiStudyImportRoute
  ApiStudyMediaRoute: typeof ApiStudyMediaRoute
  ApiStudyMigrateRoute: typeof ApiStudyMigrateRoute
  ApiStudyNotesRoute: typeof ApiStudyNotesRoute
  ApiStudyPlanningRoute: typeof ApiStudyPlanningRoute
  ApiStudyPreferencesRoute: typeof ApiStudyPreferencesRoute
  ApiStudyQueueRoute: typeof ApiStudyQueueRoute
  ApiStudyReviewsRoute: typeof ApiStudyReviewsRoute
  ApiStudySessionsRoute: typeof ApiStudySessionsRoute
  ApiStudySyncRoute: typeof ApiStudySyncRoute
  ApiStudyTrialRoute: typeof ApiStudyTrialRoute
  ApiStudyUndoRoute: typeof ApiStudyUndoRoute
  ApiStudyWorkshopRoute: typeof ApiStudyWorkshopRoute
  ApiThemesExploreRoute: typeof ApiThemesExploreRoute
  ApiUserAccountRoute: typeof ApiUserAccountRoute
  ApiUserExportRoute: typeof ApiUserExportRoute
  ApiUserLocalCalendarRoute: typeof ApiUserLocalCalendarRoute
  ApiUserNotificationsRoute: typeof ApiUserNotificationsRoute
  ApiUserPreferencesRoute: typeof ApiUserPreferencesRoute
  ApiUserProfileImageRoute: typeof ApiUserProfileImageRoute
  ApiUserThemeBuilderRoute: typeof ApiUserThemeBuilderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-open/': {
      id: '/app-open/'
      path: '/app-open'
      fullPath: '/app-open/'
      preLoaderRoute: typeof AppOpenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/open': {
      id: '/app/open'
      path: '/app/open'
      fullPath: '/app/open'
      preLoaderRoute: typeof AppOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/readiness': {
      id: '/api/readiness'
      path: '/api/readiness'
      fullPath: '/api/readiness'
      preLoaderRoute: typeof ApiReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/theme-builder': {
      id: '/api/user/theme-builder'
      path: '/api/user/theme-builder'
      fullPath: '/api/user/theme-builder'
      preLoaderRoute: typeof ApiUserThemeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/profile-image': {
      id: '/api/user/profile-image'
      path: '/api/user/profile-image'
      fullPath: '/api/user/profile-image'
      preLoaderRoute: typeof ApiUserProfileImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/preferences': {
      id: '/api/user/preferences'
      path: '/api/user/preferences'
      fullPath: '/api/user/preferences'
      preLoaderRoute: typeof ApiUserPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/notifications': {
      id: '/api/user/notifications'
      path: '/api/user/notifications'
      fullPath: '/api/user/notifications'
      preLoaderRoute: typeof ApiUserNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/local-calendar': {
      id: '/api/user/local-calendar'
      path: '/api/user/local-calendar'
      fullPath: '/api/user/local-calendar'
      preLoaderRoute: typeof ApiUserLocalCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/export': {
      id: '/api/user/export'
      path: '/api/user/export'
      fullPath: '/api/user/export'
      preLoaderRoute: typeof ApiUserExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/account': {
      id: '/api/user/account'
      path: '/api/user/account'
      fullPath: '/api/user/account'
      preLoaderRoute: typeof ApiUserAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/themes/explore': {
      id: '/api/themes/explore'
      path: '/api/themes/explore'
      fullPath: '/api/themes/explore'
      preLoaderRoute: typeof ApiThemesExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study/workshop': {
      id: '/api/study/workshop'
      path: '/api/study/workshop'
      fullPath: '/api/study/workshop'
      preLoaderRoute: typeof ApiStudyWorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study/undo': {
      id: '/api/study/undo'
      path: '/api/study/undo'
      fullPath: '/api/study/undo'
      preLoaderRoute: typeof ApiStudyUndoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study/trial': {
      id: '/api/study/trial'
      path: '/api/study/trial'
      fullPath: '/api/study/trial'
      preLoaderRoute: typeof ApiStudyTrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study/sync': {
      id: '/api/study/sync'
      path: '/api/study/sync'
      fullPath: '/api/study/sync'
      preLoaderRoute: typeof ApiStudySyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study/sessions': {
      id: '/api/study/sessions'
      path: '/api/study/sessions'
      fullPath: '/api/study/sessions'
      preLoaderRoute: typeof ApiStudySessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study/reviews': {
      id: '/api/study/reviews'
      path: '/api/study/reviews'
      fullPath: '/api/study/reviews'
      preLoaderRoute: typeof ApiStudyReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study/queue': {
      id: '/api/study/queue'
      path: '/api/study/queue'
      fullPath: '/api/study/queue'
      preLoaderRoute: typeof ApiStudyQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study/preferences': {
      id: '/api/study/preferences'
      path: '/api/study/preferences'
      fullPath: '/api/study/preferences'
      preLoaderRoute: typeof ApiStudyPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study/planning': {
      id: '/api/study/planning'
      path: '/api/study/planning'
      fullPath: '/api/study/planning'
      preLoaderRoute: typeof ApiStudyPlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study/notes': {
      id: '/api/study/notes'
      path: '/api/study/notes'
      fullPath: '/api/study/notes'
      preLoaderRoute: typeof ApiStudyNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study/migrate': {
      id: '/api/study/migrate'
      path: '/api/study/migrate'
      fullPath: '/api/study/migrate'
      preLoaderRoute: typeof ApiStudyMigrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study/media': {
      id: '/api/study/media'
      path: '/api/study/media'
      fullPath: '/api/study/media'
      preLoaderRoute: typeof ApiStudyMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study/import': {
      id: '/api/study/import'
      path: '/api/study/import'
      fullPath: '/api/study/import'
      preLoaderRoute: typeof ApiStudyImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study/flashcards': {
      id: '/api/study/flashcards'
      path: '/api/study/flashcards'
      fullPath: '/api/study/flashcards'
      preLoaderRoute: typeof ApiStudyFlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study/export': {
      id: '/api/study/export'
      path: '/api/study/export'
      fullPath: '/api/study/export'
      preLoaderRoute: typeof ApiStudyExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study/decks': {
      id: '/api/study/decks'
      path: '/api/study/decks'
      fullPath: '/api/study/decks'
      preLoaderRoute: typeof ApiStudyDecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study/cutover': {
      id: '/api/study/cutover'
      path: '/api/study/cutover'
      fullPath: '/api/study/cutover'
      preLoaderRoute: typeof ApiStudyCutoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study/browser': {
      id: '/api/study/browser'
      path: '/api/study/browser'
      fullPath: '/api/study/browser'
      preLoaderRoute: typeof ApiStudyBrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study/bootstrap': {
      id: '/api/study/bootstrap'
      path: '/api/study/bootstrap'
      fullPath: '/api/study/bootstrap'
      preLoaderRoute: typeof ApiStudyBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study/analytics': {
      id: '/api/study/analytics'
      path: '/api/study/analytics'
      fullPath: '/api/study/analytics'
      preLoaderRoute: typeof ApiStudyAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/pdf': {
      id: '/api/reports/pdf'
      path: '/api/reports/pdf'
      fullPath: '/api/reports/pdf'
      preLoaderRoute: typeof ApiReportsPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/annotations': {
      id: '/api/reports/annotations'
      path: '/api/reports/annotations'
      fullPath: '/api/reports/annotations'
      preLoaderRoute: typeof ApiReportsAnnotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/sync': {
      id: '/api/portal/sync'
      path: '/api/portal/sync'
      fullPath: '/api/portal/sync'
      preLoaderRoute: typeof ApiPortalSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/login': {
      id: '/api/portal/login'
      path: '/api/portal/login'
      fullPath: '/api/portal/login'
      preLoaderRoute: typeof ApiPortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/data': {
      id: '/api/portal/data'
      path: '/api/portal/data'
      fullPath: '/api/portal/data'
      preLoaderRoute: typeof ApiPortalDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/account': {
      id: '/api/portal/account'
      path: '/api/portal/account'
      fullPath: '/api/portal/account'
      preLoaderRoute: typeof ApiPortalAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/past-papers/share': {
      id: '/api/past-papers/share'
      path: '/api/past-papers/share'
      fullPath: '/api/past-papers/share'
      preLoaderRoute: typeof ApiPastPapersShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/past-papers/saves': {
      id: '/api/past-papers/saves'
      path: '/api/past-papers/saves'
      fullPath: '/api/past-papers/saves'
      preLoaderRoute: typeof ApiPastPapersSavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/past-papers/reindex': {
      id: '/api/past-papers/reindex'
      path: '/api/past-papers/reindex'
      fullPath: '/api/past-papers/reindex'
      preLoaderRoute: typeof ApiPastPapersReindexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/past-papers/preferences': {
      id: '/api/past-papers/preferences'
      path: '/api/past-papers/preferences'
      fullPath: '/api/past-papers/preferences'
      preLoaderRoute: typeof ApiPastPapersPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/past-papers/pdf': {
      id: '/api/past-papers/pdf'
      path: '/api/past-papers/pdf'
      fullPath: '/api/past-papers/pdf'
      preLoaderRoute: typeof ApiPastPapersPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/past-papers/library': {
      id: '/api/past-papers/library'
      path: '/api/past-papers/library'
      fullPath: '/api/past-papers/library'
      preLoaderRoute: typeof ApiPastPapersLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/past-papers/browse': {
      id: '/api/past-papers/browse'
      path: '/api/past-papers/browse'
      fullPath: '/api/past-papers/browse'
      preLoaderRoute: typeof ApiPastPapersBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/past-papers/attempts': {
      id: '/api/past-papers/attempts'
      path: '/api/past-papers/attempts'
      fullPath: '/api/past-papers/attempts'
      preLoaderRoute: typeof ApiPastPapersAttemptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/past-papers/annotations': {
      id: '/api/past-papers/annotations'
      path: '/api/past-papers/annotations'
      fullPath: '/api/past-papers/annotations'
      preLoaderRoute: typeof ApiPastPapersAnnotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback/suspension': {
      id: '/api/feedback/suspension'
      path: '/api/feedback/suspension'
      fullPath: '/api/feedback/suspension'
      preLoaderRoute: typeof ApiFeedbackSuspensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback/reports': {
      id: '/api/feedback/reports'
      path: '/api/feedback/reports'
      fullPath: '/api/feedback/reports'
      preLoaderRoute: typeof ApiFeedbackReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desktop/release': {
      id: '/api/desktop/release'
      path: '/api/desktop/release'
      fullPath: '/api/desktop/release'
      preLoaderRoute: typeof ApiDesktopReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desktop/login-token': {
      id: '/api/desktop/login-token'
      path: '/api/desktop/login-token'
      fullPath: '/api/desktop/login-token'
      preLoaderRoute: typeof ApiDesktopLoginTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desktop/bootstrap': {
      id: '/api/desktop/bootstrap'
      path: '/api/desktop/bootstrap'
      fullPath: '/api/desktop/bootstrap'
      preLoaderRoute: typeof ApiDesktopBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/retention': {
      id: '/api/cron/retention'
      path: '/api/cron/retention'
      fullPath: '/api/cron/retention'
      preLoaderRoute: typeof ApiCronRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/classroom/sync-sessions': {
      id: '/api/classroom/sync-sessions'
      path: '/api/classroom/sync-sessions'
      fullPath: '/api/classroom/sync-sessions'
      preLoaderRoute: typeof ApiClassroomSyncSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/classroom/data': {
      id: '/api/classroom/data'
      path: '/api/classroom/data'
      fullPath: '/api/classroom/data'
      preLoaderRoute: typeof ApiClassroomDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/changelog/bumps': {
      id: '/api/changelog/bumps'
      path: '/api/changelog/bumps'
      fullPath: '/api/changelog/bumps'
      preLoaderRoute: typeof ApiChangelogBumpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/unlink': {
      id: '/api/calendar/unlink'
      path: '/api/calendar/unlink'
      fullPath: '/api/calendar/unlink'
      preLoaderRoute: typeof ApiCalendarUnlinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/events': {
      id: '/api/calendar/events'
      path: '/api/calendar/events'
      fullPath: '/api/calendar/events'
      preLoaderRoute: typeof ApiCalendarEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/event': {
      id: '/api/calendar/event'
      path: '/api/calendar/event'
      fullPath: '/api/calendar/event'
      preLoaderRoute: typeof ApiCalendarEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/create': {
      id: '/api/calendar/create'
      path: '/api/calendar/create'
      fullPath: '/api/calendar/create'
      preLoaderRoute: typeof ApiCalendarCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/calendars': {
      id: '/api/calendar/calendars'
      path: '/api/calendar/calendars'
      fullPath: '/api/calendar/calendars'
      preLoaderRoute: typeof ApiCalendarCalendarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/status': {
      id: '/api/billing/status'
      path: '/api/billing/status'
      fullPath: '/api/billing/status'
      preLoaderRoute: typeof ApiBillingStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/portal': {
      id: '/api/billing/portal'
      path: '/api/billing/portal'
      fullPath: '/api/billing/portal'
      preLoaderRoute: typeof ApiBillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/token-login': {
      id: '/api/auth/token-login'
      path: '/api/auth/token-login'
      fullPath: '/api/auth/token-login'
      preLoaderRoute: typeof ApiAuthTokenLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/forgot-password': {
      id: '/api/auth/forgot-password'
      path: '/api/auth/forgot-password'
      fullPath: '/api/auth/forgot-password'
      preLoaderRoute: typeof ApiAuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant/state': {
      id: '/api/assistant/state'
      path: '/api/assistant/state'
      fullPath: '/api/assistant/state'
      preLoaderRoute: typeof ApiAssistantStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant/skill-writer': {
      id: '/api/assistant/skill-writer'
      path: '/api/assistant/skill-writer'
      fullPath: '/api/assistant/skill-writer'
      preLoaderRoute: typeof ApiAssistantSkillWriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant/providers': {
      id: '/api/assistant/providers'
      path: '/api/assistant/providers'
      fullPath: '/api/assistant/providers'
      preLoaderRoute: typeof ApiAssistantProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant/context': {
      id: '/api/assistant/context'
      path: '/api/assistant/context'
      fullPath: '/api/assistant/context'
      preLoaderRoute: typeof ApiAssistantContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant/chat': {
      id: '/api/assistant/chat'
      path: '/api/assistant/chat'
      fullPath: '/api/assistant/chat'
      preLoaderRoute: typeof ApiAssistantChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/app/session': {
      id: '/api/app/session'
      path: '/api/app/session'
      fullPath: '/api/app/session'
      preLoaderRoute: typeof ApiAppSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/github-issues': {
      id: '/api/admin/github-issues'
      path: '/api/admin/github-issues'
      fullPath: '/api/admin/github-issues'
      preLoaderRoute: typeof ApiAdminGithubIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/feedback': {
      id: '/api/admin/feedback'
      path: '/api/admin/feedback'
      fullPath: '/api/admin/feedback'
      preLoaderRoute: typeof ApiAdminFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/classroom/sync-sessions/$sessionId': {
      id: '/api/classroom/sync-sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/api/classroom/sync-sessions/$sessionId'
      preLoaderRoute: typeof ApiClassroomSyncSessionsSessionIdRouteImport
      parentRoute: typeof ApiClassroomSyncSessionsRoute
    }
    '/api/classroom/sync-sessions/$sessionId/upload': {
      id: '/api/classroom/sync-sessions/$sessionId/upload'
      path: '/upload'
      fullPath: '/api/classroom/sync-sessions/$sessionId/upload'
      preLoaderRoute: typeof ApiClassroomSyncSessionsSessionIdUploadRouteImport
      parentRoute: typeof ApiClassroomSyncSessionsSessionIdRoute
    }
  }
}

interface ApiClassroomSyncSessionsSessionIdRouteChildren {
  ApiClassroomSyncSessionsSessionIdUploadRoute: typeof ApiClassroomSyncSessionsSessionIdUploadRoute
}

const ApiClassroomSyncSessionsSessionIdRouteChildren: ApiClassroomSyncSessionsSessionIdRouteChildren =
  {
    ApiClassroomSyncSessionsSessionIdUploadRoute:
      ApiClassroomSyncSessionsSessionIdUploadRoute,
  }

const ApiClassroomSyncSessionsSessionIdRouteWithChildren =
  ApiClassroomSyncSessionsSessionIdRoute._addFileChildren(
    ApiClassroomSyncSessionsSessionIdRouteChildren,
  )

interface ApiClassroomSyncSessionsRouteChildren {
  ApiClassroomSyncSessionsSessionIdRoute: typeof ApiClassroomSyncSessionsSessionIdRouteWithChildren
}

const ApiClassroomSyncSessionsRouteChildren: ApiClassroomSyncSessionsRouteChildren =
  {
    ApiClassroomSyncSessionsSessionIdRoute:
      ApiClassroomSyncSessionsSessionIdRouteWithChildren,
  }

const ApiClassroomSyncSessionsRouteWithChildren =
  ApiClassroomSyncSessionsRoute._addFileChildren(
    ApiClassroomSyncSessionsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  ChangelogRoute: ChangelogRoute,
  DashboardRoute: DashboardRoute,
  DownloadRoute: DownloadRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  UpdatesRoute: UpdatesRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiReadinessRoute: ApiReadinessRoute,
  AppOpenRoute: AppOpenRoute,
  AppOpenIndexRoute: AppOpenIndexRoute,
  ApiAdminFeedbackRoute: ApiAdminFeedbackRoute,
  ApiAdminGithubIssuesRoute: ApiAdminGithubIssuesRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAppSessionRoute: ApiAppSessionRoute,
  ApiAssistantChatRoute: ApiAssistantChatRoute,
  ApiAssistantContextRoute: ApiAssistantContextRoute,
  ApiAssistantProvidersRoute: ApiAssistantProvidersRoute,
  ApiAssistantSkillWriterRoute: ApiAssistantSkillWriterRoute,
  ApiAssistantStateRoute: ApiAssistantStateRoute,
  ApiAuthForgotPasswordRoute: ApiAuthForgotPasswordRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthTokenLoginRoute: ApiAuthTokenLoginRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingPortalRoute: ApiBillingPortalRoute,
  ApiBillingStatusRoute: ApiBillingStatusRoute,
  ApiCalendarCalendarsRoute: ApiCalendarCalendarsRoute,
  ApiCalendarCreateRoute: ApiCalendarCreateRoute,
  ApiCalendarEventRoute: ApiCalendarEventRoute,
  ApiCalendarEventsRoute: ApiCalendarEventsRoute,
  ApiCalendarUnlinkRoute: ApiCalendarUnlinkRoute,
  ApiChangelogBumpsRoute: ApiChangelogBumpsRoute,
  ApiClassroomDataRoute: ApiClassroomDataRoute,
  ApiClassroomSyncSessionsRoute: ApiClassroomSyncSessionsRouteWithChildren,
  ApiCronRetentionRoute: ApiCronRetentionRoute,
  ApiDesktopBootstrapRoute: ApiDesktopBootstrapRoute,
  ApiDesktopLoginTokenRoute: ApiDesktopLoginTokenRoute,
  ApiDesktopReleaseRoute: ApiDesktopReleaseRoute,
  ApiFeedbackReportsRoute: ApiFeedbackReportsRoute,
  ApiFeedbackSuspensionRoute: ApiFeedbackSuspensionRoute,
  ApiPastPapersAnnotationsRoute: ApiPastPapersAnnotationsRoute,
  ApiPastPapersAttemptsRoute: ApiPastPapersAttemptsRoute,
  ApiPastPapersBrowseRoute: ApiPastPapersBrowseRoute,
  ApiPastPapersLibraryRoute: ApiPastPapersLibraryRoute,
  ApiPastPapersPdfRoute: ApiPastPapersPdfRoute,
  ApiPastPapersPreferencesRoute: ApiPastPapersPreferencesRoute,
  ApiPastPapersReindexRoute: ApiPastPapersReindexRoute,
  ApiPastPapersSavesRoute: ApiPastPapersSavesRoute,
  ApiPastPapersShareRoute: ApiPastPapersShareRoute,
  ApiPortalAccountRoute: ApiPortalAccountRoute,
  ApiPortalDataRoute: ApiPortalDataRoute,
  ApiPortalLoginRoute: ApiPortalLoginRoute,
  ApiPortalSyncRoute: ApiPortalSyncRoute,
  ApiReportsAnnotationsRoute: ApiReportsAnnotationsRoute,
  ApiReportsPdfRoute: ApiReportsPdfRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiStudyAnalyticsRoute: ApiStudyAnalyticsRoute,
  ApiStudyBootstrapRoute: ApiStudyBootstrapRoute,
  ApiStudyBrowserRoute: ApiStudyBrowserRoute,
  ApiStudyCutoverRoute: ApiStudyCutoverRoute,
  ApiStudyDecksRoute: ApiStudyDecksRoute,
  ApiStudyExportRoute: ApiStudyExportRoute,
  ApiStudyFlashcardsRoute: ApiStudyFlashcardsRoute,
  ApiStudyImportRoute: ApiStudyImportRoute,
  ApiStudyMediaRoute: ApiStudyMediaRoute,
  ApiStudyMigrateRoute: ApiStudyMigrateRoute,
  ApiStudyNotesRoute: ApiStudyNotesRoute,
  ApiStudyPlanningRoute: ApiStudyPlanningRoute,
  ApiStudyPreferencesRoute: ApiStudyPreferencesRoute,
  ApiStudyQueueRoute: ApiStudyQueueRoute,
  ApiStudyReviewsRoute: ApiStudyReviewsRoute,
  ApiStudySessionsRoute: ApiStudySessionsRoute,
  ApiStudySyncRoute: ApiStudySyncRoute,
  ApiStudyTrialRoute: ApiStudyTrialRoute,
  ApiStudyUndoRoute: ApiStudyUndoRoute,
  ApiStudyWorkshopRoute: ApiStudyWorkshopRoute,
  ApiThemesExploreRoute: ApiThemesExploreRoute,
  ApiUserAccountRoute: ApiUserAccountRoute,
  ApiUserExportRoute: ApiUserExportRoute,
  ApiUserLocalCalendarRoute: ApiUserLocalCalendarRoute,
  ApiUserNotificationsRoute: ApiUserNotificationsRoute,
  ApiUserPreferencesRoute: ApiUserPreferencesRoute,
  ApiUserProfileImageRoute: ApiUserProfileImageRoute,
  ApiUserThemeBuilderRoute: ApiUserThemeBuilderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
